language: node_js

node_js:
  - "node"

install:
  - npm install

script:
  - cd demo
  - (cd 1-simple && npm install && npm run build)
  - (cd 2-events && npm install && npm run build)
  - (cd 3-hierarchy && npm install && npm run build)
  - (cd 4-todo && npm install && npm run build)
  - (cd 5-pingpong && npm install && npm run build)
  - (cd 6-logging && npm install && npm run build)
  - (cd 7-ts && npm install && npm run build)
  - (cd 8-prime && npm install && npm run build)
  - npm test
